name: AlexNet-10c_1xb32_MNIST-224x224
# {module_info}_{pretrain_info}_{training_info}_{data_info}, alexnet-10class_1gpux32batch_MNIST
task:
  target: Tasks.ImageClassification.ImageClassificationTask
  params:
    model_config:
      target: models.ImageClassification.AlexNet
      params: # params for __init__
        in_channels: 1
        num_classes: 10
    loss_config:
      target: losses.ClassificationTask.CrossEntropyLoss.CrossEntropyLoss # torch.nn.CrossEntropy

data:
  target: datasets.MNIST.MNIST_Resize224x224
  params: # params for __init__
    data_dir: data
    batch_size:
    - 32
    - 64
    - 1
    train_val_split: 0.2

lightning: # params for lightning
  base_learning_rate: 4.5e-06
  # learning_rate: 0.001
  trainer:
    accelerator: gpu
    accumulate_grad_batches: 1